packageExtensions:
  "@nestjs/cli@*":
    peerDependencies:
      webpack: "*"
    peerDependenciesMeta:
      webpack:
        optional: true
  "@nestjs/core@*":
    peerDependencies:
      class-validator: "*"
    peerDependenciesMeta:
      "@nestjs/microservices":
        optional: true
      "@nestjs/platform-express":
        optional: true
      "@nestjs/websockets":
        optional: true
      class-validator:
        optional: true
  "@nestjs/graphql@*":
    peerDependencies:
      apollo-server-express: "*"
  typeorm@*:
    peerDependencies:
      pg: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-3.2.0.cjs
