version: '3.8'

services:
  client-web:
    build:
      context: .
      dockerfile: Dockerfile
      target: release
    image: client-web
    container_name: client-web
    environment:
      PORT: 80
    ports:
      - 80:80
