export const HMR_SERVER_UPDATE_MESSAGE = 'HMR_SERVER_UPDATE_MESSAGE';
export const HMR_SERVER_CONNECTED_MESSAGE = 'HMR_SERVER_CONNECTED_MESSAGE';
export const HMR_SERVER_DISCONNECTED_MESSAGE = 'HMR_SERVER_DISCONNECTED_MESSAGE';

export const HMR_FAILED_MODULE_HOT_STATUSES = ['abort', 'failed'];
